# Paramètres du site
title: Not a blog yet
email: xavier@cazin.info
description: > # this means to ignore newlines until "baseurl:"
 Bac à sable pour creuser des tunnels et faire des pâtés, pas des châteaux. 
 Jekyll et GitHub tiennent lieu de pelles, rateaux. Si ça prend forme, ou que la mer s'éloigne
 suffisamment, il n'est pas exclu que ça devienne un blog. 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xcazin
github_username:  xcazin

# Build settings
markdown: kramdown
